app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path:   /login
    defaults:  { _controller: AppBundle:Security:login }
login_check:
    path:   /login_check

logout:
    path:   /logout

app_bundle_api:
    type:     rest
    prefix:   /api
    resource: "@AppBundle/Resources/config/api-rest-routing.yml"
