security:
## En el caso que los usuarios tengan la contraseña cifrada configuramos los encoders para la entidad en la que estén los usuarios
    encoders:
        AppBundle\Entity\Administrator:
            algorithm: md5
            encode_as_base64: false
            iterations: 0
            ignore_case: false
# En providers le indicamos que los usuarios van a salir de la base de datos y el username será email
    providers:
        db_provider:
            entity: {class: AppBundle:Administrator, property: user}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

# Configuramos el firewall main para indicarle el provider, la login_path, login_check y el path del logout
        secured_area:
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: /logout
                target: /login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }

## To get started with security, check out the documentation:
## http://symfony.com/doc/current/security.html
#security:
#
#    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
#    providers:
#        in_memory:
#            memory: ~
#
#    firewalls:
#        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            anonymous: ~
#            # activate different ways to authenticate
#
#            # http_basic: ~
#            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#
#            # form_login: ~
#            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
