api_users:
    type: rest
    resource: "@AppBundle/Controller/api/UsersController.php"
    name_prefix:  api_users_

api_progenitors:
    type: rest
    resource: "@AppBundle/Controller/api/ProgenitorsController.php"
    name_prefix:  api_progenitors_

api_circulars:
    type: rest
    resource: "@AppBundle/Controller/api/CircularsController.php"
    name_prefix:  api_circulars_